chore(ci): remove support for node 4 and 5
Node versions 4 and 5 had only best-effort support. They stopped working
correctly on Windows in Appveyor, likely because Appveyor defaults to
installing a Yarn version too new to suppor them. The specific error is:

yarn install --frozen-lockfile
C:\Program Files (x86)\Yarn\lib\cli.js:46099
  let {
      ^
SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (C:\Program Files (x86)\Yarn\lib\v8-compile-cache.js:226:18)

Also, fix the version range in package.json engines to match our
supported version list.

BREAKING CHANGE:

Stop running CI for Node versions 4 and 5, to remove best-effort support
for these versions. We are not intentionally breaking compatability with
them, but compatabililty may break with them at some time in the future
without notice.